miProyectoHD/about/urls.py
from django.urls import path
from .views import about

app_name= 'about'
urlpatterns=[
    path('', about, name='about')
]

miProyectoHD/home/urls.py
from django.urls import path
from .views import home

app_name = 'home'

urlpatterns = [
    path('', home, name='home'),
]

miProyectoHD/miProyectoHD/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('sintactico/', include('sintactico.urls')),
]

miProyectoHD/sintactico/urls.py
from django.urls import path
from .views import enviar, sintactico

app_name= 'sintactico'
urlpatterns=[
    path('', sintactico, name='sintactico'),
    path('grafo/', enviar, name='grafo')
]

miProyectoHD/about/models.py
from django.db import models

# Create your models here.

miProyectoHD/home/models.py
from django.db import models

# Create your models here.
class Paciente(models.Model):
    name = models.CharField(max_length=50)
    
    class Meta:
        verbose_name = "Paciente"
        verbose_name_plural = "Pacientes"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Paciente_detail", kwargs={"pk": self.pk})


class Tessiu(models.Model):
    temperatura = models.FloatField()
    color = models.FloatField()
    inflamation= models.FloatField(verbose_name="inflamación")
    name = models.ForeignKey(Paciente, blank=True, null=True, verbose_name="nombre", on_delete=models.CASCADE)

    class Meta:
        verbose_name = ("Tejido")
        verbose_name_plural = ("Tejidos")

    def __str__(self):
        if self.name is not None:
            return str(self.temperatura)
        else:
            return str(self.temperatura)

    def get_absolute_url(self):
        return reverse("Tejido_detail", kwargs={"pk": self.pk})

miProyectoHD/sintactico/models.py
from django.db import models

# Create your models here.

miProyectoHD/about/views.py
from django.shortcuts import render

# Create your views here.

def about(request):
    #return HttpResponse('Bienvenido a casa')
    template_name= 'about\index.html'
    return render(request, template_name, {})

miProyectoHD/home/views.py
from django.shortcuts import render
from .models import Tessiu

# Create your views here.

def home(request):
    #return HttpResponse('Bienvenido a casa')
    L=Tessiu.objects.get_queryset()

    diccionario={'lista':L}

    template_name= 'home\index.html'
    return render(request, template_name, diccionario)

miProyectoHD/sintactico/views.py
from django.shortcuts import render
from home.models import Tessiu
import math

# Create your views here.

L=Tessiu.objects.get_queryset()

def sintactico(request):

    diccionario={'lista':L, 'distan':distancias,}
    template_name= 'sintactico\index.html'
    return render(request, template_name, diccionario)

def dist(lista):
    matriz = []
    for x in lista:
        fila=[]
        for y in lista:
            d= math.sqrt(((x.temperatura - y.temperatura)**2) + ((x.color - y.color)**2) + ((x.inflamation - y.inflamation)**2))
            fila.append(d)
        matriz.append(fila)
    return matriz

distancias=dist(L)

def grafo (distancias, umbral):
    tabla=[]
    for x in range(len(distancias)):
        filaDist=distancias[x]
        for y in range(len(distancias)):
            if y>=x:
                if filaDist[y]<umbral:
                    tabla.append(['R'+str(x+1),'R'+str(y+1),filaDist[y],'Si'])
                else:
                    tabla.append(['R'+str(x+1),'R'+str(y+1),filaDist[y],'No'])
    print(len(tabla))
    return tabla

def enviar(request):
    template_name= 'sintactico\index.html'

    if(request.method == 'POST'):
        umbral = int(request.POST['umbral'])
        print(umbral)
    tabla=grafo(distancias,umbral)

    diccionario={'lista':L, 'distan':distancias, 'grafo':tabla}
    return render(request, template_name, diccionario)
    

miProyectoHD/about/templates/about/index.html
{% extends 'header.html' %} {% block contenido %}
<h1>About</h1>
{% endblock contenido %}

miProyectoHD/home/templates/header.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reconocimiento de Patrones</title>
</head>
<header>
    <ul>
        <li> <a href="{% url 'home:home' %}"> Home </a> </li>
        <li> <a href="{% url 'about:about' %}"> About </a> </li>
        <li> <a href="{% url 'sintactico:sintactico' %}"> Sintactico </a> </li>
    </ul>
</header>

<body>
    {% block contenido %} {% endblock contenido %}
</body>

</html>

miProyectoHD/home/templates/home/index.html
{% extends 'header.html' %} {% block contenido %}
<h1>Curso de Reconocimiento de Patrones Sintáctico Estructural</h1>
<h1>Octubre: Mes del Cáncer e mama</h1>

<table style="border: 1px solid blue;">
    <thead>
        <tr>
            <th>ID</th>
            <th>Temperatura</th>
            <th>Color</th>
            <th>Inflamación</th>
        </tr>
    </thead>
    <tbody>
        {% for elemento in lista %}
        <tr>
            <td style="border: 1px solid blue;">{{elemento.pk}}</td>

            {% if elemento.temperatura > 50 %}
            <td style="border: 1px solid red;">{{elemento.temperatura}}</td>
            {% else %}
            <td style="border: 1px solid blue;">{{elemento.temperatura}}</td>
            {% endif %}

            <td style="border: 1px solid blue;">{{elemento.color}}</td>
            <td style="border: 1px solid blue;">{{elemento.inflamation}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock contenido %}

miProyectoHD/sintactico/templates/sintactico/index.html
{% extends 'header.html' %} {% block contenido %}
<h1>Sintactico</h1>

<div style="height: 500px; overflow-x: scroll; overflow-y: scroll;">
    <table style="border: 1px solid blue;">
        <thead>
            <tr>
                <th></th>
                {% for fila in lista %}
                <th>R{{forloop.counter}}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for fila in distan %}
            <tr>
                <th>R{{forloop.counter}}</th>
                {% for columna in fila %}
                <td style="border: 1px solid blue;">{{columna}}</td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<h2> </h2>
<h1>Grafo</h1>

<form action="{% url 'sintactico:grafo' %}" method="post">
    {% csrf_token %}
    <input type="text" name="umbral">
    <input type="submit" value="Recargar">
</form>

<div style="height: 500px; width: 300px; overflow-y: scroll;">
    <table style="border: 1px solid blue;">
        <thead>
            <tr>
                <th>Vo</th>
                <th>Vf</th>
                <th>d</th>
                <th>Si/No</th>
            </tr>
        </thead>
        <tbody>
            {% for registro in grafo %}
            <tr>
                {% for columna in registro %}
                <td style="border: 1px solid blue;">{{columna}}</td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


{% endblock contenido %}